spring.application.name=BankingCardClient

# MSSQL Connection
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=TESTDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=cekelatangin
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# LOG
logging.file.name=logs/application.log
logging.level.com.example.clientsystem.client=INFO